### ISSUE TITLE
Expose public constructor for CSVSniffer and CSVConstraintsBuilder

### ISSUE THREAD

**Issue by asm0dey** [jferard/pgloaderutils#15]
For them to be used from external applications.

**Comment by jferard** [comment]
Hi Paul. Thanks for the issue. This project is not very active, but your concern is a good reason to work on it.

For `CSVConstraintsBuilder`, there are two static methods in `CSVConstraints` (`builder` and `basicBuilder`) hence I think a direct access to the constructor is not needed. Is it ok for you?

For `CSVSniffer`, you are right: there is no way to create a `CSVSniffer` now. I will fix it as soon as possible.

**Comment by asm0dey** [comment]
BTW, today I've implemented version, equivalent to Python's CSV sniffer: https://gist.github.com/asm0dey/de74f7dc6b99ff6e4fe7ed2eb0ca38fc
It finds delimiters almost everywhere, even in pretty complex cases when delimiter is `q` for example.

**Comment by jferard** [comment]
Nice. I like the Python CSV and it's good to have a Kotlin version. (It's always a pleasure to read Kotlin code...)

> It finds delimiters almost everywhere, even in pretty complex cases when delimiter is `q` for example.

My goal here was slightly different: *given some constraints*, find the CSV format and load the data into a Postgres base. 

Typical use case is: one may use one of (`|, \t`) delimiter, a windows or unix end of line and an encoding that is `iso` or `utf-8`, the minimum number of columns is known. I have to load the data in a database as fast as possible.
